### ISSUE TITLE
Reduce .shadow_box_black border to 2px

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#1]

**Comment by Xelaty** [comment]
@polevaultweb I dont know , do you want it only for black , or other too? for now changed for black

**Comment by polevaultweb** [comment]
All the grey borders of 3px to 2px please

**Comment by Xelaty** [comment]
@polevaultweb changed

**Comment by polevaultweb** [comment]
Looks good, but perhaps use a shared class for those kind of boxes?

**Comment by Xelaty** [comment]
@polevaultweb i dont know how to better do it , i can create a variable with border size and shadow size

**Comment by polevaultweb** [comment]
You would do something like:

`<div class="shadow_box shadow_box_blue">`

```
.shadow_box {
    border: 2px solid #9c9c9c;
    background: white;
    &.shadow_box_blue {
        10px 10px 0px 0px #a5eff2
    }
    &.shadow_box_black {
        10px 10px 0px 0px #3c3c3b
    }
    &.shadow_box_pink {
         ...
     }
}
```
