### ISSUE TITLE
Footer tweaks

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#10]
- Black footer text needs to be normal case
- Reduce size of font in pink and green footers
- Make much smaller on mobile so keep on one line
![image](https://user-images.githubusercontent.com/1770201/62126209-14e07080-b2c7-11e9-80dc-727247ac49fb.png)

**Comment by Xelaty** [comment]
1) done

**Comment by Xelaty** [comment]
2. i reduced font but if i try to insert in one line for mobile it looks bad  
![image](https://user-images.githubusercontent.com/35823610/62206460-8a694100-b39a-11e9-8b08-41713c613487.png)

**Comment by polevaultweb** [comment]
Thats fine as is 👍
