### ISSUE TITLE
Page for resource-single

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#13]
There isn't a PSD annoyingly but can you use https://www.dropbox.com/s/k2xiwynbpwpv3m0/PrintPlayLearn%20INDIVIDUAL%20RESOURCE.jpg?dl=0

**Comment by Xelaty** [comment]
@polevaultweb will complete tommorow, it normally for you? i didnt see this

**Comment by polevaultweb** [comment]
That's fine. Not your fault - i overlooked the missing PSD too

**Comment by Xelaty** [comment]
@polevaultweb  http://u276440394.hostingerapp.com/resource.html
