### ISSUE TITLE
Mobile: Top header reduce size

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#16]
![image](https://user-images.githubusercontent.com/1770201/62125312-b0241680-b2c4-11e9-843f-412abd85dc8b.png)

Make the icons smaller and text so links fit on one line

**Comment by Xelaty** [comment]
@polevaultweb done , iphone 5s 
![image](https://user-images.githubusercontent.com/35823610/62206523-ab319680-b39a-11e9-94ee-6273c555c0c9.png)
