### ISSUE TITLE
Use heading elements

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#2]
Eg. homepage, 
- h1 in the slider
- h2 "To get started..."
- h3 "Im a teacher"

etc

**Comment by polevaultweb** [comment]
h2 on needs to be font-weigh: bold

**Comment by Xelaty** [comment]
@polevaultweb do it on home , in other pages in welcome container i used h2

**Comment by polevaultweb** [comment]
@Xelaty ah yeah, as long as all the pages have headings please
