### ISSUE TITLE
Mobile: reduce height of hero image

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#20]
![image](https://user-images.githubusercontent.com/1770201/62125760-f332b980-b2c5-11e9-97e1-072738a507e2.png)

make the bottom margin below the text the same as the top margin.

**Comment by Xelaty** [comment]
@polevaultweb  http://u276440394.hostingerapp.com/contact.html

**Comment by polevaultweb** [comment]
@Xelaty looks good. Can you keep the text centered? It goes left aligned on small screen

**Comment by Xelaty** [comment]
@polevaultweb text centered
