### ISSUE TITLE
Mobile: Responsive

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#22]
Teacher Parent boxes should stay on one line at >= 980px

![image](https://user-images.githubusercontent.com/1770201/62125972-8e2b9380-b2c6-11e9-86b1-d75c5d553c71.png)

**Comment by Xelaty** [comment]
@polevaultweb done for 998px , if you want i can create new one media query

**Comment by Xelaty** [comment]
http://u276440394.hostingerapp.com/index.html

**Comment by polevaultweb** [comment]
Great, can you also make these three appear on one line at the same breakpoint 
![image](https://user-images.githubusercontent.com/1770201/62208598-4290ec80-b38f-11e9-9ec1-9d18b5e48d45.png)

**Comment by Xelaty** [comment]
@polevaultweb fixed , created grid like in blog posts
