### ISSUE TITLE
Mobile: Green sub nav height too big

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#24]
![image](https://user-images.githubusercontent.com/1770201/62208661-70763100-b38f-11e9-9ff7-ca0beac175aa.png)

Should be like a bigger width: 

![image](https://user-images.githubusercontent.com/1770201/62208694-7ec44d00-b38f-11e9-90f9-869bf637ccc7.png)

**Comment by Xelaty** [comment]
@polevaultweb http://u276440394.hostingerapp.com/resources.html - fixed
