### ISSUE TITLE
Box header needs more padding

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#4]
shadow_box_green box_title needs to have more horizontal padding to match PSD

**Comment by polevaultweb** [comment]
![image](https://user-images.githubusercontent.com/1770201/62124127-58d07700-b2c1-11e9-99ff-c6f0fc48386d.png)

![image](https://user-images.githubusercontent.com/1770201/62124134-5d952b00-b2c1-11e9-92e6-fd27bbe57e80.png)

**Comment by Xelaty** [comment]
@polevaultweb done it for now for desktop , need to fix for mobile . i think to complete fully desktop version and then create styles for mobile

**Comment by polevaultweb** [comment]
I think it looks fine on mobile as it is now. But need to apply to same other boxes eg. Meet Michell
