### ISSUE TITLE
Home: About image bottom needs lining up with text box

### ISSUE THREAD

**Issue by polevaultweb** [Xelaty/printplay-layout#6]
![image](https://user-images.githubusercontent.com/1770201/62124270-b95fb400-b2c1-11e9-91a8-2fd381699ee0.png)

**Comment by Xelaty** [comment]
![image](https://user-images.githubusercontent.com/35823610/62207294-77f00700-b39c-11e9-9eb9-7c8b1ef35ae0.png)
@polevaultweb  fixed
